edc.participant.id=minimal-participant
# Server básico (usa valores por defecto si se omiten path/port). Definimos explícito para claridad.
web.http.port=8181
web.http.path=/api
edc.monitor.level=INFO
