name: minimal-connector

services:
  connector:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
      args:
        JAR: minimal-connector.jar
    image: minimal-connector:latest
    restart: unless-stopped
    volumes:
      - ./configuration.properties:/app/configuration.properties:ro
    ports:
      - "8181:8181" # Endpoint health
    # Para limpiar contenedores huérfanos de versiones previas: `docker compose down --remove-orphans`
